PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dbpedia-owl: <http://dbpedia.org/ontology/>
PREFIX dbpprop: <http://dbpedia.org/property/>

SELECT DISTINCT ?nom ?pc ?insee
WHERE{
  {
    ?r foaf:name ?nom .
    ?r dbpedia-owl:postalCode ?pc .
    OPTIONAL { ?r dbpprop:insee ?insee} .
    FILTER (?pc = 44000) .
  }
  UNION
  {
    ?r foaf:name ?nom .
    ?r dbpprop:insee ?insee .    
    OPTIONAL { ?r dbpedia-owl:postalCode ?pc} .
    FILTER (?insee = 44109) .
  }
}